package cl.clarochile.aplicaciones.evalcrediticia.performfullcreditevaluation.servicio;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import com.amx.service.adapter.PerformFullCreditEvaluationResponseAdapterImpl;
import com.amx.service.bean.EntFceTO;
import com.amx.service.bean.SalFceTO;
import com.amx.service.business.PerformFullCreditEvaluationBusiness;
import com.amx.service.validator.Validator;

import cl.clarochile.aplicaciones.evalcrediticia.performfullcreditevaluation.estructura.PerformFullCreditEvaluationRequest;
import cl.clarochile.aplicaciones.evalcrediticia.performfullcreditevaluation.estructura.PerformFullCreditEvaluationResponse;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "PerformFullCreditEvaluationPort", serviceName = "PerformFullCreditEvaluationService", targetNamespace = "http://servicio.performfullcreditevaluation.evalCrediticia.aplicaciones.clarochile.cl", endpointInterface = "cl.clarochile.aplicaciones.evalcrediticia.performfullcreditevaluation.servicio.PerformFullCreditEvaluation")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class PerformFullCreditEvaluationService_PerformFullCreditEvaluationPortImpl  extends SpringBeanAutowiringSupport implements PerformFullCreditEvaluation {
	private static Logger logger = Logger.getLogger(PerformFullCreditEvaluationService_PerformFullCreditEvaluationPortImpl.class);

	@Autowired
	private PerformFullCreditEvaluationBusiness miFullBusinees;
	public PerformFullCreditEvaluationService_PerformFullCreditEvaluationPortImpl() {
	}

	/**
	 * 
	 * @param body
	 * @return returns
	 *         cl.clarochile.aplicaciones.evalcrediticia.performfullcreditevaluation
	 *         .estructura.PerformFullCreditEvaluationResponse
	 * @throws BusinessExceptionFault
	 */
	public PerformFullCreditEvaluationResponse performFullCreditEvaluation(PerformFullCreditEvaluationRequest body) throws BusinessExceptionFault {
		
		EntFceTO miEntFceTO = null;
		SalFceTO miSalFCETO = null;
		PerformFullCreditEvaluationResponse response = null;
		
		try {
			if (Validator.validateFCE(body).length() == 0) {
				miEntFceTO = PerformFullCreditEvaluationResponseAdapterImpl.casoRequestTypeToBean(body);
				miSalFCETO = miFullBusinees.performFullCreditEvaluation(miEntFceTO);
				response = PerformFullCreditEvaluationResponseAdapterImpl.datosCasoBeanToType(miSalFCETO);
				response.setReglasAplicadas(null);
			}
		} catch (Exception e) {
			logger.error(e.getMessage());

			cl.clarochile.aplicaciones.evalcrediticia.commonsexceptions.BusinessExceptionFault faultInfo = new cl.clarochile.aplicaciones.evalcrediticia.commonsexceptions.BusinessExceptionFault();

			faultInfo.setErrorCode("001");
			faultInfo.setErrorMsg("Error interno del Motor");
			faultInfo.setMessage("Evaluacion Crediticia");
			BusinessExceptionFault business = new BusinessExceptionFault(null, faultInfo);
			throw business;
		}

		return response;
	}
	/**
	 * 
	 * @param body
	 * @return returns
	 *         cl.clarochile.aplicaciones.evalcrediticia.performfullcreditevaluation
	 *         .estructura.PerformFullCreditEvaluationResponse
	 * @throws BusinessExceptionFault
	 */
	public PerformFullCreditEvaluationResponse performFullCreditEvaluationTest(PerformFullCreditEvaluationRequest body) throws BusinessExceptionFault {
		EntFceTO miEntFceTO = null;
		SalFceTO miSalFCETO = null;
		PerformFullCreditEvaluationResponse response = null;
		
		try {
			if (Validator.validateFCE(body).length() == 0) {
				miEntFceTO = PerformFullCreditEvaluationResponseAdapterImpl.casoRequestTypeToBean(body);
				miSalFCETO = miFullBusinees.performFullCreditEvaluation(miEntFceTO);
				response = PerformFullCreditEvaluationResponseAdapterImpl.datosCasoBeanToType(miSalFCETO);
			}
		} catch (Exception e) {
			logger.error(e.getMessage());

			cl.clarochile.aplicaciones.evalcrediticia.commonsexceptions.BusinessExceptionFault faultInfo = new cl.clarochile.aplicaciones.evalcrediticia.commonsexceptions.BusinessExceptionFault();

			faultInfo.setErrorCode("001");
			faultInfo.setErrorMsg("Error interno del Motor");
			faultInfo.setMessage("Evaluacion Crediticia");
			BusinessExceptionFault business = new BusinessExceptionFault(null, faultInfo);
			throw business;
		}

		return response;
	}

}
