package cl.clarochile.aplicaciones.evalcrediticia.getcreditscorebycustomer.servicio;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.context.support.SpringBeanAutowiringSupport;

import com.amx.service.adapter.GetCreditScoreByCustomerAdapter;
import com.amx.service.bean.EntLceTO;
import com.amx.service.bean.SalLceTO;
import com.amx.service.business.GetCreditScoreByCustomerBusiness;
import com.amx.service.business.GetCreditScoreByCustomerBusinessImpl;

import cl.clarochile.aplicaciones.evalcrediticia.getcreditscorebycustomer.estructura.GetCreditScoreByCustomerRequest;
import cl.clarochile.aplicaciones.evalcrediticia.getcreditscorebycustomer.estructura.GetCreditScoreByCustomerResponse;
import cl.clarochile.aplicaciones.evalcrediticia.validator.Validator;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "GetCreditScoreByCustomerPort", serviceName = "GetCreditScoreByCustomerService", targetNamespace = "http://servicio.getcreditscorebycustomer.evalCrediticia.aplicaciones.clarochile.cl", endpointInterface = "cl.clarochile.aplicaciones.evalcrediticia.getcreditscorebycustomer.servicio.GetCreditScoreByCustomer")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class GetCreditScoreByCustomerService_GetCreditScoreByCustomerPortImpl
		extends SpringBeanAutowiringSupport implements GetCreditScoreByCustomer {

	private static Logger logger = Logger
			.getLogger(GetCreditScoreByCustomerService_GetCreditScoreByCustomerPortImpl.class);

	@Autowired
	GetCreditScoreByCustomerBusinessImpl getCreditScoreByCustomerBusinessImpl;

	public GetCreditScoreByCustomerService_GetCreditScoreByCustomerPortImpl() {
	}

	/**
	 * 
	 * @param body
	 * @return returns
	 *         cl.clarochile.aplicaciones.evalcrediticia.getcreditscorebycustomer
	 *         .estructura.GetCreditScoreByCustomerResponse
	 * @throws BusinessExceptionFault
	 */
	public GetCreditScoreByCustomerResponse getCreditScoreByCustomer(
			GetCreditScoreByCustomerRequest body) throws BusinessExceptionFault {
		GetCreditScoreByCustomerResponse getCreditScoreByCustomerResponse = null;
		EntLceTO entLceTO = null;
		SalLceTO salLceTO = null;
		String validacion = Validator.validateLCE(body).toString();
		try {
			if (validacion.isEmpty()) {
				entLceTO = GetCreditScoreByCustomerAdapter.typeToBean(body);
				salLceTO = getCreditScoreByCustomerBusinessImpl
						.getCreditScoreByCustomer(entLceTO);
				getCreditScoreByCustomerResponse = GetCreditScoreByCustomerAdapter
						.beanToType(salLceTO);
				getCreditScoreByCustomerResponse.setReglasAplicadas(null);

			} else {
				throw new Exception(validacion);
			}
		} catch (Exception e) {
			logger.error(e.getMessage());

			cl.clarochile.aplicaciones.evalcrediticia.commonsexceptions.BusinessExceptionFault faultInfo = new cl.clarochile.aplicaciones.evalcrediticia.commonsexceptions.BusinessExceptionFault();

			faultInfo.setErrorCode("001");
			faultInfo.setErrorMsg("Error interno del Motor");
			faultInfo.setMessage("Evaluacion Crediticia");
			BusinessExceptionFault business = new BusinessExceptionFault(
					e.getMessage(), faultInfo);
			throw business;
		}
		return getCreditScoreByCustomerResponse;
	}

	/**
	 * 
	 * @param body
	 * @return returns
	 *         cl.clarochile.aplicaciones.evalcrediticia.getcreditscorebycustomer
	 *         .estructura.GetCreditScoreByCustomerResponse
	 * @throws BusinessExceptionFault
	 */
	public GetCreditScoreByCustomerResponse getCreditScoreByCustomerTest(
			GetCreditScoreByCustomerRequest body) throws BusinessExceptionFault {
		GetCreditScoreByCustomerResponse getCreditScoreByCustomerResponse = null;
		EntLceTO entLceTO = null;
		SalLceTO salLceTO = null;

		String validacion = Validator.validateLCE(body).toString();
		try {
			if (validacion.isEmpty()) {
				entLceTO = GetCreditScoreByCustomerAdapter.typeToBean(body);
				salLceTO = getCreditScoreByCustomerBusinessImpl
						.getCreditScoreByCustomer(entLceTO);
				getCreditScoreByCustomerResponse = GetCreditScoreByCustomerAdapter
						.beanToType(salLceTO);
			} else {
				throw new Exception(validacion);
			}
		} catch (Exception e) {
			logger.error(e.getMessage());

			cl.clarochile.aplicaciones.evalcrediticia.commonsexceptions.BusinessExceptionFault faultInfo = new cl.clarochile.aplicaciones.evalcrediticia.commonsexceptions.BusinessExceptionFault();

			faultInfo.setErrorCode("001");
			faultInfo.setErrorMsg("Error interno del Motor");
			faultInfo.setMessage("Evaluacion Crediticia ");
			BusinessExceptionFault business = new BusinessExceptionFault(
					e.getMessage(), faultInfo);
			throw business;
		}
		return getCreditScoreByCustomerResponse;
	}

}
